### ISSUE TITLE
Add icon in card header

### ISSUE THREAD

**Issue by iurynogueira** [iurynogueira/ion#115]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/6165180/188140252-281733dd-4dc5-414c-be7d-1f1f378a5592.png">

**Comment by jairochaves2** [comment]
@iurynogueira deve ser utilizado string com o nome do ícone, ou um TemplateRef?

**Comment by iurynogueira** [comment]
> @iurynogueira deve ser utilizado string com o nome do ícone, ou um TemplateRef?

use ion-icon component
