### ISSUE TITLE
Button CSS changes

### ISSUE THREAD

**Issue by iurynogueira** [iurynogueira/ion#167]
change color $primary-6 to $primary-color

**Comment by anirudh0806** [comment]
could you please assign me this work?

**Comment by sumit-022** [comment]
Please assign this work to me

**Comment by Anurag-Singh-04** [comment]
Hey @iurynogueira I would like to work on this issue, could you please assign this to me.

**Comment by iurynogueira** [comment]
> could you please assign me this work?

Done! 😄
