### ISSUE TITLE
Add new files icons

### ISSUE THREAD

**Issue by iurynogueira** [iurynogueira/ion#173]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/6165180/194077686-668f74d2-86a4-41b1-8d69-9591b11c65a9.png">

**Comment by bloodmonk7** [comment]
I would like to take this up
(New file icon will be provided by you or I have to find one?)

**Comment by jairochaves2** [comment]
Hi, @bloodmonk7. These are the icons, the first two have already been added.
![doc-check](https://user-images.githubusercontent.com/15896994/194397317-992fe13d-1d5d-4e3c-93d5-f11896268d18.svg)
![doc-close](https://user-images.githubusercontent.com/15896994/194397319-cd9138fa-fa5d-4d28-82b8-53d441a90e0c.svg)
![doc-warning](https://user-images.githubusercontent.com/15896994/194397320-c744eab3-ca32-4d92-988e-38b9b294cfe1.svg)

**Comment by jairochaves2** [comment]
Hi, @bloodmonk7. these are the icons, the first two have already been added.
http://shorturl.at/beow8

**Comment by bloodmonk7** [comment]
Shall I replace the three left ones?

**Comment by jairochaves2** [comment]
Add this three. They are on this link http://shorturl.at/beow8
![image](https://user-images.githubusercontent.com/15896994/194552720-015675c5-4e79-4cec-9f19-1627a028be59.png)

**Comment by jairochaves2** [comment]
The task is similar to this.

https://github.com/iurynogueira/ion/pull/106/files

**Comment by bloodmonk7** [comment]
Working on it, can you assign it to me @jairochaves2
