### ISSUE TITLE
Create template no data content for table

### ISSUE THREAD

**Issue by AlyssonMascarenhas** [iurynogueira/ion#336]
Currently, if an empty data is passed to the table, its body is not rendered.

![image (2)](https://user-images.githubusercontent.com/54484070/204809905-46230637-aa71-4906-958c-168e4dfd2f30.png)

Sugiro a implementação de um template usado caso o data seja vazio:

![image](https://user-images.githubusercontent.com/54484070/204810250-a8c6dd86-adf9-4394-bc2c-4a3dfae0f54e.png)

**Comment by andersonnagelo** [comment]
![image](https://user-images.githubusercontent.com/31452157/204850434-6cc220c5-6532-428a-bd9f-99f66910ec83.png)
