### ISSUE TITLE
feat: ellipsis on table cell

### ISSUE THREAD

**Issue by mizek1** [iurynogueira/ion#758]
Sometimes we have a large information to show on a column, that makes a cell too large on both aspects, width and height:

![image](https://github.com/Brisanet/ion/assets/57760325/97f4957a-ee14-4907-85c3-047f643bb25f)

We need to be able to, when we set a width on a column, we can also set if that column could be partially hidden using ellipsis properties. We also need that, when we decide to use ellipsis on a column, the table automatically shows a tooltip with the complete information. Something like this:

![image](https://github.com/Brisanet/ion/assets/57760325/35a4296b-a8d0-41a0-aae4-c9ee2d3e127e)

**Comment by luccskywalker** [comment]
Qual o sentido de ter uma tabela que esconde o que eu estrou mostrando nela? 
Esse comportamento me parece mais um acordion do que uma tabela.

**Comment by mizek1** [comment]
> Qual o sentido de ter uma tabela que esconde o que eu estou mostrando nela? 
> Esse comportamento me parece mais um acordion do que uma tabela. 

The default behavior is to show all information, this feat will only allow the possibility to hide part of the information that can be hidden. Every project has it's own specifications.

**Comment by mizek1** [comment]
What do you guys think of these solution? Any other idea to solve this problem?
@iurynogueira @andersonnagelo @Jeter-Megaron @qrayannes (I can't find Edney's user)

**Comment by luccskywalker** [comment]
If the user is not finding the information that him needs, the column is not representing their necessity.

**Comment by edneyql** [comment]
@mizek1 @luccskywalker  Sometimes the solution may not be a table, the solution could be related to another component... As I don't understand the context of the demand itself, I can't say so much if in this case it would be a table or not , but regarding the density of information, it also interferes with the user's cognitive process and loses the meaning of the component that serves to systematize the information, which must be presented in a clear and precise way, to facilitate the reading and understanding of the data. If I have a table that brings me such a high density of data and I can't deal logically with it, I have to rethink whether I'm using the right component for the solution.

**Comment by AlyssonMascarenhas** [comment]
@edneyql what if the table is just a way to extract through actions?

**Comment by AlyssonMascarenhas** [comment]
I believe we can create a discussion at github.com/Brisanet/ion/discussions instead of discussing it here in the issue.

**Comment by Jeter-Megaron** [comment]
The solution has already been aligned with the SIGA team, we are going to suppress the column information in the table, the user will be able to see all the data related to the selected profile with 1 additional click on the detailing column of the desired line.

**Comment by iurynogueira** [comment]
Guys, can follow with this implementation because can have other cases to use this abbreviation too. We need give other options to the dev and this improve will be more one.
